/**
 * Guards the runtime translation merge against a regression that is invisible
 * in English.
 *
 * `RUNTIME_TRANSLATIONS` is assembled from several batches written at different
 * times. The later ones (notably `runtimeVfsTranslations.ts`) are generated by
 * `registerLines`, which writes an entry for *every* line of a document —
 * including the lines a translator left in English. Under a plain object spread
 * the last batch wins unconditionally, so one English line copied verbatim into
 * an otherwise-translated block silently reverted a translation an earlier batch
 * had already made.
 *
 * That is not hypothetical: the paired redaction lines
 * `PHASE ███ IS ██████ UNDERWAY` / `"PHASE TWO IS ALREADY UNDERWAY"` and the
 * psi-report prompt `> Enter phrase: ___________` were all translated in the
 * base and wave-2 batches and all rendered in English in every language.
 */
import { describe, it, expect } from 'vitest';
import { RUNTIME_TRANSLATIONS } from '../runtime';

const LANGS = ['pt-BR', 'es'] as const;

describe('runtime translation merge', () => {
  it('never lets an untranslated line displace a translation another batch made', () => {
    // These three all live in a late VFS batch as English-for-English entries
    // and in an earlier batch as real translations. The merge must keep the
    // translation.
    const contested = [
      '  PHASE ███ IS ██████ UNDERWAY',
      '  "PHASE TWO IS ALREADY UNDERWAY"',
      '  > Enter phrase: ___________',
    ];

    for (const lang of LANGS) {
      for (const key of contested) {
        expect(
          RUNTIME_TRANSLATIONS[lang][key],
          `${lang} renders ${JSON.stringify(key)} in English`
        ).not.toBe(key);
      }
    }
  });

  it('keeps the redaction puzzle internally consistent in every language', () => {
    // The keycard states the clearance string; the memo shows the same line with
    // words blacked out. A player matches one against the other, so whatever
    // survives redaction in the memo must still appear, in order, in the
    // keycard — otherwise the two halves of the puzzle stop lining up once
    // translated.
    const KEYCARD = '  "PHASE TWO IS ALREADY UNDERWAY"';
    const MEMO = '  PHASE ███ IS ██████ UNDERWAY';

    for (const lang of [...LANGS, 'en'] as const) {
      const keycard = lang === 'en' ? KEYCARD : RUNTIME_TRANSLATIONS[lang][KEYCARD];
      const memo = lang === 'en' ? MEMO : RUNTIME_TRANSLATIONS[lang][MEMO];

      const visible = memo
        .split(/█+/)
        .map(s => s.trim())
        .filter(Boolean);
      expect(visible.length, `${lang}: memo lost its redaction blocks`).toBeGreaterThan(1);

      let cursor = 0;
      for (const fragment of visible) {
        const at = keycard.indexOf(fragment, cursor);
        expect(
          at,
          `${lang}: memo fragment ${JSON.stringify(fragment)} is missing from, or out of order in, the keycard line ${JSON.stringify(keycard)}`
        ).toBeGreaterThanOrEqual(0);
        cursor = at + fragment.length;
      }
    }
  });
});
