/**
 * Codegen: reads app/data/endingsContent.json (source of truth) and writes:
 *   1. app/engine/generated/endingsContent.generated.ts  (English ENDINGS content)
 *   2. app/i18n/generated/endingsSupplement.generated.ts  (pt-BR/es ending translations)
 * Both files are generated — do not edit by hand.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

type Locale = 'pt-BR' | 'es';
type EndingRecord = {
  fields: unknown;
  translations: Record<Locale, Record<string, string>>;
};
type FieldLocales = Record<string, Partial<Record<Locale, string>>>;
type EndingRecordV2 = EndingRecord & { fieldLocales?: FieldLocales };

const HEADER =
  '// AUTO-GENERATED by scripts/gen-endings-from-content.ts — DO NOT EDIT.\n' +
  '// Edit app/data/endingsContent.json and run `npm run gen:endings-from-content`.\n\n';

/**
 * Merge every ending's translations into two dictionaries keyed by English
 * string. Priority: explicit per-field locale edits (fieldLocales) override the
 * passthrough `translations` map. `fields` supplies the English key for each
 * per-field edit.
 */
export function buildSupplement(
  content: Record<string, EndingRecordV2>
): Record<Locale, Record<string, string>> {
  const merged: Record<Locale, Record<string, string>> = { 'pt-BR': {}, es: {} };
  for (const rec of Object.values(content)) {
    for (const locale of ['pt-BR', 'es'] as const) {
      Object.assign(merged[locale], rec.translations[locale]);
    }
    if (rec.fieldLocales) {
      const f = rec.fields as {
        title: string;
        subtitle: string;
        ufo74_final: string;
        narrative: string[];
        aol: { headline: string; subheadline: string; imageAlt: string; body: string[] };
      };
      const englishFor = (key: string): string | undefined => {
        if (key === 'title') return f.title;
        if (key === 'subtitle') return f.subtitle;
        if (key === 'ufo74_final') return f.ufo74_final;
        if (key === 'aol.headline') return f.aol.headline;
        if (key === 'aol.subheadline') return f.aol.subheadline;
        if (key === 'aol.imageAlt') return f.aol.imageAlt;
        const nm = key.match(/^narrative\[(\d+)\]$/);
        if (nm) return f.narrative[Number(nm[1])];
        const bm = key.match(/^aol\.body\[(\d+)\]$/);
        if (bm) return f.aol.body[Number(bm[1])];
        return undefined;
      };
      for (const [fieldKey, locales] of Object.entries(rec.fieldLocales)) {
        const en = englishFor(fieldKey);
        if (!en) continue;
        for (const locale of ['pt-BR', 'es'] as const) {
          const val = locales[locale];
          if (val) merged[locale][en] = val;
        }
      }
    }
  }
  return merged;
}

async function writeFormattedFile(filePath: string, source: string): Promise<void> {
  const config = (await resolveConfig(filePath)) ?? {};
  const formatted = await format(source, { ...config, filepath: filePath });
  writeFileSync(filePath, formatted, 'utf-8');
}

async function generate(): Promise<void> {
  const contentPath = resolve(import.meta.dirname, '../app/data/endingsContent.json');
  const content = JSON.parse(readFileSync(contentPath, 'utf-8')) as Record<string, EndingRecordV2>;

  // 1. English content module.
  const fields: Record<string, unknown> = {};
  for (const [id, rec] of Object.entries(content)) fields[id] = rec.fields;
  const contentTs =
    HEADER +
    "import type { EndingId, GameEnding } from '../endings';\n\n" +
    "export const ENDINGS_CONTENT: Record<EndingId, Omit<GameEnding, 'id'>> =\n" +
    JSON.stringify(fields, null, 2) +
    ';\n';

  const contentDir = resolve(import.meta.dirname, '../app/engine/generated');
  mkdirSync(contentDir, { recursive: true });
  await writeFormattedFile(resolve(contentDir, 'endingsContent.generated.ts'), contentTs);

  // 2. Translations module.
  const merged = buildSupplement(content);
  const suppTs =
    HEADER +
    'type RuntimeDictionary = Record<string, string>;\n\n' +
    "export const ENDINGS_SUPPLEMENT: Record<'pt-BR' | 'es', RuntimeDictionary> =\n" +
    JSON.stringify(merged, null, 2) +
    ';\n';

  const suppDir = resolve(import.meta.dirname, '../app/i18n/generated');
  mkdirSync(suppDir, { recursive: true });
  await writeFormattedFile(resolve(suppDir, 'endingsSupplement.generated.ts'), suppTs);

  console.log('generated endingsContent.generated.ts + endingsSupplement.generated.ts');
}

// Only write files when run directly (not when imported by tests).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  generate().catch(error => {
    console.error(error);
    process.exitCode = 1;
  });
}
