/**
 * Codegen: reads app/data/endingsContent.json (source of truth) and writes:
 *   1. app/engine/generated/endingsContent.generated.ts  (English ENDINGS content)
 *   2. app/i18n/generated/endingsSupplement.generated.ts  (pt-BR/es ending translations)
 * Both files are generated — do not edit by hand.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

type Locale = 'pt-BR' | 'es';
type EndingRecord = {
  fields: unknown;
  translations: Record<Locale, Record<string, string>>;
};

const contentPath = resolve(import.meta.dirname, '../app/data/endingsContent.json');
const content = JSON.parse(readFileSync(contentPath, 'utf-8')) as Record<string, EndingRecord>;

const HEADER =
  '// AUTO-GENERATED by scripts/gen-endings-from-content.ts — DO NOT EDIT.\n' +
  '// Edit app/data/endingsContent.json and run `npm run gen:endings-from-content`.\n\n';

// 1. English content module.
const fields: Record<string, unknown> = {};
for (const [id, rec] of Object.entries(content)) fields[id] = rec.fields;
const contentTs =
  HEADER +
  "import type { EndingId, GameEnding } from '../endings';\n\n" +
  "export const ENDINGS_CONTENT: Record<EndingId, Omit<GameEnding, 'id'>> =\n" +
  JSON.stringify(fields, null, 2) +
  ';\n';

const contentDir = resolve(import.meta.dirname, '../app/engine/generated');
mkdirSync(contentDir, { recursive: true });
writeFileSync(resolve(contentDir, 'endingsContent.generated.ts'), contentTs, 'utf-8');

// 2. Translations module.
const merged: Record<Locale, Record<string, string>> = { 'pt-BR': {}, es: {} };
for (const rec of Object.values(content)) {
  for (const locale of ['pt-BR', 'es'] as const) {
    Object.assign(merged[locale], rec.translations[locale]);
  }
}
const suppTs =
  HEADER +
  'type RuntimeDictionary = Record<string, string>;\n\n' +
  "export const ENDINGS_SUPPLEMENT: Record<'pt-BR' | 'es', RuntimeDictionary> =\n" +
  JSON.stringify(merged, null, 2) +
  ';\n';

const suppDir = resolve(import.meta.dirname, '../app/i18n/generated');
mkdirSync(suppDir, { recursive: true });
writeFileSync(resolve(suppDir, 'endingsSupplement.generated.ts'), suppTs, 'utf-8');

console.log('generated endingsContent.generated.ts + endingsSupplement.generated.ts');
